// @flow
const actionTypes = {
  REQUEST_ACCESS_TOKEN: 'REQUEST_ACCESS_TOKEN',
  RECEIVE_ACCESS_TOKEN: 'RECEIVE_ACCESS_TOKEN',
  ACCESS_TOKEN_ERROR: 'ACCESS_TOKEN_ERROR',
  REQUEST_CHANNELS: 'REQUEST_CHANNELS',
  RECEIVE_CHANNELS: 'RECEIVE_CHANNELS',
  CHANNELS_ERROR: 'CHANNELS_ERROR',
  TOGGLE_CHANNEL_LIST: 'TOGGLE_CHANNEL_LIST',
  SELECT_CHANNEL: 'SELECT_CHANNEL'
};

export default actionTypes;
